### ISSUE TITLE
Cannot change order of transaction history

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2697]
Changing order from "Newest" to "Oldest" results in an infinite stakey dance. "Loading more transactions..." never stops.

![Screenshot from 2020-10-07 12-29-26](https://user-images.githubusercontent.com/6762864/95325234-cbab8980-0898-11eb-9891-3db24fbb6c34.png)

**Comment by vctt94** [comment]
Do you have txs at this wallet?

**Comment by jholdstock** [comment]
I do

![Peek 2020-10-07 14-20](https://user-images.githubusercontent.com/6762864/95336166-4334e500-08a8-11eb-9580-5e0f4e057fa9.gif)

**Comment by jholdstock** [comment]
I've also recreated this with 2x mainnet wallets. Using current dcrd and dcrwallet master.

**Comment by vctt94** [comment]
Great, I think I can reproduce it now

**Comment by victorgcramos** [comment]
This is fixed by https://github.com/decred/decrediton/pull/2706

**Comment by jholdstock** [comment]
@ay-p can this be re-opened please, I am still seeing this issue with everything running on master.

Layout is changed by #2706 but behaviour shown in the gif above is still occuring. @vctt94 @victorgcramos feel free to DM if you need more info to reproduce

**Comment by jholdstock** [comment]
Found some errors in the decrediton log:

```
2020-10-20 15:16:19.662 [ERR] GRPC: Unary method /walletrpc.WalletService/GetTransaction invoked by 127.0.0.1:55198 errored: rpc error: code = NotFound desc = wallet.TransactionSummary(9257f9f44b2208040d624d14f02de7abf2258293b70fb956557759da97f2fd2d): item does not exist
```

This transaction is not found on dcrdata, so it likely does not exist at all. However, I am seeing the same error on three different wallets (2x mainnet, 1x testnet). Each error has a different tx ID. All IDs are missing on dcrdata

**Comment by vctt94** [comment]
Can you still reproduce this?

**Comment by jholdstock** [comment]
Yep, I still see this. Even on a wallet with only 12 transactions.

![Peek 2020-10-30 08-36](https://user-images.githubusercontent.com/6762864/97717970-485b0d80-1abd-11eb-9b03-b4f8ddd9dcb9.gif)
