### ISSUE TITLE
SPV mode icon missing

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3036]
Missing SPV mode icon with errors in console window. This is with rc4 on Windows 10. Screenshot below has some parts cut out for privacy.

![image](https://user-images.githubusercontent.com/5420838/100925419-98a40180-34a7-11eb-9e87-8a3b5c581580.png)

**Comment by jholdstock** [comment]
I am unable to recreate this on RC4 or master.

Note that something was fixed in this area recently #2996 - can you please ensure you are using up-to-date code

**Comment by sumiflow** [comment]
I only installed the pre-built binary from https://github.com/decred/decred-binaries/releases/tag/v1.6.0-rc4
Perhaps it's already fixed in master but just didn't make the cut into the rc4 binary

**Comment by jholdstock** [comment]
hm, strange. I can see the commit from #2996 on the 1.6-rc4 tag - https://github.com/decred/decrediton/commits/v1.6.0-rc4

I guess we can keep this open in case anybody else encounters it, but I dont really see anything to fix here.  Ping @alexlyp in case he knows something about the RC build which I might be unaware of.

**Comment by sumiflow** [comment]
I'm still having the same issue with rc5:
1. I uninstalled decrediton and deleted all traces of any files that I could find under my user account
2. I installed the rc5.exe binary for windows from here: https://github.com/decred/decred-binaries/releases/tag/v1.6.0-rc5
3. I created a brand new wallet with new seed and selected SPV mode
4. I get the javacript errors and missing icon shown below. You can see the 'alt' text for the icon but not the icon itself.

![image](https://user-images.githubusercontent.com/5420838/104755827-9678c800-5720-11eb-90e1-7bc23e67de9b.png)

**Comment by sumiflow** [comment]
I encountered the same issue on a separate machine that I upgraded from 1.5.2 to 1.6 rc5 as well.
@alexlyp I wonder if everyone who installs the rc5 tagged build on windows has this issue
