### ISSUE TITLE
Startup Error in MacOS, Connection to dcrd failed, please try and reconnect. Connects after retry

### ISSUE THREAD

**Issue by africanalex** [decred/decrediton#402]
I am getting the following error when starting decrediton on mac osx. 

Error: Connection to RPC server failed: dial tcp [::1]:9109: getsockopt: connection refused. You may need to edit /Library/Application Support/decrediton/config.json and try again

debug is: 

dcrd started with pid: 56543
Starting dcrwallet with --configfile=/Library/Application Support/decrediton/dcrwallet.conf,--piperx=4
dcrwallet started with pid: 56544
15:24:15 2017-05-22 [INF] DCRD: Version 1.0.1+release (Go version go1.7.5)
15:24:15 2017-05-22 [INF] DCRW: Version 1.0.1+release (Go version go1.7.5)
15:24:15 2017-05-22 [INF] DCRD: Home dir: /Library/Application Support/Dcrd
15:24:15 2017-05-22 [INF] DCRW: Generating TLS certificates...
15:24:15 2017-05-22 [INF] DCRD: Loading block database from '/Library/Application Support/Dcrd/data/mainnet/blocks_ffldb'
15:24:15 2017-05-22 [INF] DCRW: Done generating TLS certificates
15:24:15 2017-05-22 [INF] DCRD: Block database loaded
15:24:15 2017-05-22 [INF] DCRW: Experimental RPC server listening on 127.0.0.1:9112
15:24:15 2017-05-22 [INF] INDX: Exists address index is enabled
15:24:15 2017-05-22 [INF] STKE: Stake database version 1 loaded
15:24:15 2017-05-22 [INF] CHAN: Blockchain database version 2 loaded
15:24:15 2017-05-22 [INF] CHAN: Chain state: height 135404, hash 00000000000001531354322d80eb3dadc0f93e82e82c366b6dc6136877fafb22, total transactions 2308533, work 863654761906856234919, stake version 0
15:24:16 2017-05-22 [INF] GRPC: Unary method /walletrpc.VersionService/Version invoked by 127.0.0.1:58907
15:24:16 2017-05-22 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/WalletExists invoked by 127.0.0.1:58925
15:24:16 2017-05-22 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/OpenWallet invoked by 127.0.0.1:58925
15:24:19 2017-05-22 [INF] WLLT: Opened wallet
15:24:19 2017-05-22 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/StartConsensusRpc invoked by 127.0.0.1:58925
15:24:19 2017-05-22 [ERR] CHNS: Connection attempt failed: dial tcp 127.0.0.1:9109: getsockopt: connection refused
15:24:24 2017-05-22 [ERR] GRPC: Unary method /walletrpc.WalletLoaderService/StartConsensusRpc invoked by 127.0.0.1:58925 errored: rpc error: code = 5 desc = Connection to RPC server failed: dial tcp 127.0.0.1:9109: getsockopt: connection refused
15:24:24 2017-05-22 [INF] RPCS: RPC server listening on 127.0.0.1:9109
15:24:24 2017-05-22 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/StartConsensusRpc invoked by 127.0.0.1:58925
15:24:24 2017-05-22 [INF] AMGR: Loaded 2192 addresses from file '/Library/Application Support/Dcrd/data/mainnet/peers.json'
15:24:24 2017-05-22 [ERR] CHNS: Connection attempt failed: dial tcp [::1]:9109: getsockopt: connection refused
15:24:24 2017-05-22 [INF] CMGR: Server listening on 0.0.0.0:9108
15:24:24 2017-05-22 [INF] CMGR: Server listening on [::]:9108
15:24:24 2017-05-22 [INF] CMGR: 3 addresses found from DNS seed mainnet.decredseed.org
15:24:24 2017-05-22 [INF] BMGR: New valid peer 89.40.126.183:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:24 2017-05-22 [INF] BMGR: Syncing to block height 135404 from peer 89.40.126.183:9108
15:24:24 2017-05-22 [INF] BMGR: New valid peer 212.47.234.23:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:24 2017-05-22 [INF] CMGR: 38 addresses found from DNS seed mainnet-seed.decred.org
15:24:24 2017-05-22 [INF] BMGR: New valid peer 198.199.85.77:9108 (outbound) (/dcrwire:0.2.0/dcrd:0.6.1/)
15:24:24 2017-05-22 [INF] CMGR: 37 addresses found from DNS seed mainnet-seed.decred.mindcry.org
15:24:24 2017-05-22 [INF] BMGR: New valid peer 142.54.188.18:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:24 2017-05-22 [INF] CMGR: 36 addresses found from DNS seed mainnet-seed.decred.netpurgatory.com
15:24:24 2017-05-22 [INF] BMGR: New valid peer 104.159.251.219:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:24 2017-05-22 [INF] BMGR: New valid peer 104.238.152.155:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:24 2017-05-22 [INF] BMGR: New valid peer 99.65.105.3:9108 (outbound) (/dcrwire:0.2.2/dcrd:1.0.1/)
15:24:29 2017-05-22 [ERR] GRPC: Unary method /walletrpc.WalletLoaderService/StartConsensusRpc invoked by 127.0.0.1:58925 errored: rpc error: code = 5 desc = Connection to RPC server failed: dial tcp [::1]:9109: getsockopt: connection refused

**Comment by alexlyp** [comment]
So to confirm you are using the decrediton 1.0.2 release?

**Comment by africanalex** [comment]
yes it is 1.0.2, I just started it up again and it is now starting up without the error, the router has been reset since I was having the error

**Comment by alexlyp** [comment]
When you did receive the error were you sent to a screen with a "retry" button?

**Comment by africanalex** [comment]
Yes. The retry button then led to a successful connection

**Comment by alexlyp** [comment]
Ah great.  We're still trying to solve this, but essentially depending on cpu speed/arch etc, dcrd takes a little longer to prepare it's RPC server for use by dcrwallet (via decrediton).  We'll be smoothing this out in coming releases.  Thanks for the report.

**Comment by magnus-staberg** [comment]
I'm also getting this. It's not resolved in 1.0.3. It's happening each time the app has been turned off for about a day. @alexlyp , this issue should be reopened.

**Comment by alexlyp** [comment]
Reopening this issue.  As I told @magnus-staberg on Slack.  We have plans to completely revamp the opening of decrediton.  The hope is we can emulate the way Ethereum wallet bring up works: great logging/check node connectivity/various splash screens to describe what is currently occurring.  With that overhaul this issue should be resolved.

**Comment by jcvernaleo** [comment]
So I've been thinking about this and experimenting a bit.

A couple of points.

We have a couple things going on here.  First, we attempt to start dcrd and dcrwallet BEFORE the main electron app actually starts up.  Since we try to only communicate with them through rpc (json or grpc) or signals that should be fine, but it means we have no access to the launching or even status of those guys from inside decrediton proper.

Second, dcrd can take a while to start up which is kind of out of scope for us, but we need to be able to deal with it better.

Third and slightly unrelated, since we basically just have onboarding or full app, when the blockchain isn't ready, we don't give great feedback for it.

What the ethereum wallet does is starts up with a splashcreen first which can give feedback on where things are.  If we did somehting like that we could do more of the sync status there, and handle cli tool startup from there.  That would give us better control over the startup to allow recovery from slow things.  We would probably want to allow the user to click through that (as eth does) if they want to get to the main app page even though the chain isnt synced.

If that rambling all sounds good, I was going to start by moving the cli launching into the main app rather than happening before any gui stuff starts.

**Comment by magnus-staberg** [comment]
![screen shot 2017-06-23 at 14 18 56](https://user-images.githubusercontent.com/921390/27482068-248e2134-5820-11e7-8de1-95b3b4ed7c0d.png)
The error alert should be displayed in front of existing view. Mac 10.12.5, Decrediton 1.0.5.

**Comment by gabrielvincent** [comment]
Issue still happens on 1.0.6. Maybe instead of displaying immediately the reload button, Decrediton should silently fail and retry the connection to dcrd a few times before displaying the error?

**Comment by alexlyp** [comment]
Fix is in master and will be included in the next release.  

That's exactly what it does now :)

**Comment by adamljohns** [comment]
the error I'm getting is: 
Config File Error
There was an error while trying to load the config file, the format is invalid.

File: /Users/adamjohns/Library/Application Support/decrediton/config.json
Error: SyntaxError: Unexpected end of JSON input

I'm at a loss for how to solve this, but I can't find the passphrase to load the wallet on another computer, and I'm afraid I'll need it to solve this problem...  Any advice?

**Comment by magnus-staberg** [comment]
@adamljohns Is the content of config.json valid JSON format? You can test here https://jsonlint.com/ If you need more help, please visit #support channel at decred.slack.com
